### ISSUE TITLE
Update for new slash commands

### ISSUE THREAD

**Issue by DAflamingFOX** [Hopeful-Developers/Javacord-CommandHandler#2]
Javacord has finally implemented slash commands; so this should get updated eventually.
[wiki link](https://javacord.org/wiki/basic-tutorials/interactions/commands.html)

**Comment by DAflamingFOX** [comment]
I can look into this; but will need to investigate how slash commands work first.

**Comment by Hopefuls** [comment]
They're pretty easy to use, Javacord has it's own builders regarding that.
